name: MusicCompanion
options:
  bundleIdPrefix: com.allienna
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_EMIT_LOC_STRINGS: "YES"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin-Modern
    from: "1.0.0"
  # DynamicNotchKit: temporarily disabled - SwiftUICore linking issue on Tahoe
  #   url: https://github.com/MrKai77/DynamicNotchKit
  #   from: "1.0.0"

targets:
  MusicCompanion:
    type: application
    platform: macOS
    sources:
      - path: MusicCompanion
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: KeyboardShortcuts
      - package: LaunchAtLogin
      # - package: DynamicNotchKit
      - framework: ScriptingBridge.framework
        embed: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.allienna.MusicCompanion
        INFOPLIST_FILE: MusicCompanion/Resources/Info.plist
        PRODUCT_NAME: "Music Companion"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        SWIFT_OBJC_BRIDGING_HEADER: MusicCompanion/MusicCompanion-Bridging-Header.h
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
    entitlements:
      path: MusicCompanion/Resources/MusicCompanion.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.automation.apple-events: true
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-write: true

schemes:
  MusicCompanion:
    build:
      targets:
        MusicCompanion: all
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug": true
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
